### PR TITLE
Perform null checking on both Clipboard and Transferrable.

### LINKED ISSUE #5388: [BUG] NullPointerException in client if clipboard is empty during login
**Describe the bug**
The mirth client throws a NullPointerException if the clipboard is empty during login.

**Expected behavior**
Login should occur when the clipboard is empty.

**Actual behavior**
```
java.lang.NullPointerException
	at com.mirth.connect.client.ui.actions.PasteAction.isEnabled(PasteAction.java:39)
	at java.desktop/javax.swing.AbstractAction.setEnabledFromAction(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.configurePropertiesFromAction(Unknown Source)
	at java.desktop/javax.swing.JMenuItem.configurePropertiesFromAction(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.setAction(Unknown Source)
	at java.desktop/javax.swing.JPopupMenu.add(Unknown Source)
	at com.mirth.connect.client.ui.components.MirthSyntaxTextArea.<init>(MirthSyntaxTextArea.java:80)
	at com.mirth.connect.client.ui.components.MirthSyntaxTextArea.<init>(MirthSyntaxTextArea.java:53)
	at com.mirth.connect.client.ui.EditMessageDialog.initComponents(EditMessageDialog.java:435)
	at com.mirth.connect.client.ui.EditMessageDialog.<init>(EditMessageDialog.java:69)
	at com.mirth.connect.client.ui.Frame.setupFrame(Frame.java:541)
	at com.mirth.connect.client.ui.Mirth.<init>(Mirth.java:66)
	at com.mirth.connect.client.ui.LoginPanel$8.handleSuccess(LoginPanel.java:556)
	at com.mirth.connect.client.ui.LoginPanel$8.doInBackground(LoginPanel.java:445)
	at com.mirth.connect.client.ui.LoginPanel$8.doInBackground(LoginPanel.java:416)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Environment (please complete the following information):**
 - OS: Linux
 - Java Distribution/Version: OpenJDK 11
 - Connect Version: 4.1.0

**Workaround(s)**
Copy something to the clipboard before logging in.

**Additional context**
https://github.com/nextgenhealthcare/connect/blob/00c2496bb4236f1c8a5a7cedafc00abf486623f1/client/src/com/mirth/connect/client/ui/actions/PasteAction.java#L38-L39

In line 38, the call to [getContents](https://docs.oracle.com/en/java/javase/11/docs/api/java.datatransfer/java/awt/datatransfer/Clipboard.html#getContents(java.lang.Object)) can return null if the clipboard is empty, causing the exception to be thrown on line 39.

Probably just needs to return false if `contents` is null.

### PR DESCRIPTION
**Pull request by ChristopherSchultz**
Fixes #5388

### CODE REVIEW

File: client/src/com/mirth/connect/client/ui/actions/PasteAction.java [hunk 1]
```diff
@@ -35,8 +36,14 @@ public void actionPerformed(ActionEvent e) {
     public boolean isEnabled() {
         if (comp.isVisible() && comp.isEditable() && comp.isEnabled()) {
             try {
-                Transferable contents = Toolkit.getDefaultToolkit().getSystemClipboard().getContents(this);
-                return contents.isDataFlavorSupported(DataFlavor.stringFlavor);
+                Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
+                if(null != clipboard) {
```
Comment (jonbartels) [inline client/src/com/mirth/connect/client/ui/actions/PasteAction.java:40]: Is this a Yoda Condition? https://en.wikipedia.org/wiki/Yoda_conditions

This is a style issue

File: client/src/com/mirth/connect/client/ui/actions/PasteAction.java [hunk 2]
```diff
@@ -35,8 +36,14 @@ public void actionPerformed(ActionEvent e) {
     public boolean isEnabled() {
         if (comp.isVisible() && comp.isEditable() && comp.isEnabled()) {
             try {
-                Transferable contents = Toolkit.getDefaultToolkit().getSystemClipboard().getContents(this);
-                return contents.isDataFlavorSupported(DataFlavor.stringFlavor);
+                Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
+                if(null != clipboard) {
+                    Transferrable contents = clipboard.getContents(this);
+                    if(null != contents) {
+                        return contents.isDataFlavorSupported(DataFlavor.stringFlavor);
```
Comment (jonbartels) [inline client/src/com/mirth/connect/client/ui/actions/PasteAction.java:43]: Does Mirth Connect typically apply the only-one-return style or not?

File: client/src/com/mirth/connect/client/ui/actions/PasteAction.java [hunk 3]
```diff
@@ -35,8 +36,14 @@ public void actionPerformed(ActionEvent e) {
...
-                return contents.isDataFlavorSupported(DataFlavor.stringFlavor);
+                Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
+                if(null != clipboard) {
+                    Transferrable contents = clipboard.getContents(this);
+                    if(null != contents) {
+                        return contents.isDataFlavorSupported(DataFlavor.stringFlavor);
+                    }
+                }
+                return false;
             } catch (IllegalStateException e) {
```
Comment (jonbartels) [inline client/src/com/mirth/connect/client/ui/actions/PasteAction.java:47]: When would an IllegalStateException be thrown?

Should this exception be at least logged and not hidden?

File: client/src/com/mirth/connect/client/ui/actions/PasteAction.java (hunk 1 above)
Comment (jdonextgen) [reply client/src/com/mirth/connect/client/ui/actions/PasteAction.java:40]: @ChristopherSchultz Yeah, can we reverse the placement of the ```null``` and the ```clipboard``` variable in the condition? I think that'll make it more consistent with the rest of the conditions throughout Connect. So it'll look like the following instead:
```if (clipboard != null) {```

**Review by jdonextgen — CHANGES_REQUESTED** [review]
@ChristopherSchultz I left just one comment about the if condition. Otherwise, the changes look good.

File: client/src/com/mirth/connect/client/ui/actions/PasteAction.java (hunk 2 above)
Comment (jdonextgen) [reply client/src/com/mirth/connect/client/ui/actions/PasteAction.java:43]: @jonbartels No, we don't typically apply the only-one-return coding style.

File: client/src/com/mirth/connect/client/ui/actions/PasteAction.java (hunk 3 above)
Comment (jdonextgen) [reply client/src/com/mirth/connect/client/ui/actions/PasteAction.java:47]: @jonbartels Apparently the IllegalStateException can be thrown on the call to ```.getContents(this)``` if the clipboard is unavailable. The example that the documentation provided is where on some platforms, the system clipboard is unavailable if it's being accessed by another application.

I don't think we need to log this exception since a user won't be able to do anything with or within Mirth Connect to resolve it.

**Comment by jdonextgen** [comment]
@ChristopherSchultz I just merged it in, I'll make the change on my end. Thanks for the PR and @jonbartels thanks for the comments!

**Comment by ChristopherSchultz** [comment]
Sorry about ignoring the review. I didn't see it was waiting for me.

Being an old C programmer, I always avoid using lvalues as the left-hand value of a conditional. A single character can mean the difference between "is this NULL" and "this is NULL" and it's difficult to debug. No compiler will allow you to assign a value to a constant. Java compilers are smarter and will tell you that `(clipboard = null)` is not a boolean expression. Older C compilers will happily compile and run and that bug will be in there for who-know-how-long.

So my fingers have a habit that overrules my brain on this one.
